Repository UjjwalSharma01/checklist, pull requests merged in 2024-01, with the labels that each got.

#139 Text res
  styles.css
Labels: apertre, Medium

#141 added logo
  Logo/1200px-OOP.svg.png
  Logo/1lOZAtF1V7j9TeKjwbiv6UQ.jpg
  Logo/731_java.png
  Logo/C_Logo.png
  Logo/c--logo-icon-0.png
  Logo/design_algorithm_method_model_pr.png
  Logo/linux_PNG1.png
  Logo/png-clipart-go-computer-programm.png
  Logo/pngegg.png
  Logo/pngwing.com (1).png
  Logo/pngwing.com (2).png
  index.html
  styles.css
Labels: apertre, Easy

#145 Add footer in all pages
  C++_Basics.html
  C_Programming.html
  JavaBasic.html
  OOP.html
  STL.html
  Vector.html
  WebApp.html
  algorithm.html
  frontendProjects.html
  golang.html
  linux.html
  python_Basics.html
  styles.css
Labels: apertre, Easy

#149 changed UI
  dark-mode.css
  dark-mode.js
  styles.css
Labels: apertre, Hard

#159 added frontend projs
  frontendProjects.html
  styles.css
Labels: apertre, Easy

#162 css changes made to smooth out hover effects
  styles.css
Labels: apertre, Easy

#163 issue #151 done
  aos/aos.css
  aos/aos.js
  index.html
Labels: apertre, Easy

#165 Update Contact Page
  contact.css
  contact.html
  dark-mode.js
  styles.css
Labels: apertre, Easy

#168 Updat The UI of home page
  dark-mode.css
  index.html
  styles.css
Labels: apertre, Hard

#171 #164 issue added a scroll to top arrow
  index.html
  script.js
  styles.css
Labels: apertre, Easy

#173 issue #164 fixed the refresh problem of scroll to top arrow button
  index.html
  script.js
Labels: apertre, Easy

#183 Solve Problem in Back to top option
  C++_Basics.html
  C_Programming.html
  Contribute.html
  JavaBasic.html
  Logo/vector.jpeg
  OOP.html
  STL.html
  Vector.html
  WebApp.html
  algorithm.html
  golang.html
  index.html
  linux.html
  python_Basics.html
  script.js
  scrollbar.css
  scrollbar.js
Labels: apertre, Medium

#192 Add animation on scrolling
  Contribute.html
  index.html
Labels: apertre, Medium

#194 Add Footer in About Page
  Contribute.html
  Logo/fb.png
  Logo/ig.png
  Logo/twt.png
  contribute.css
Labels: apertre, Medium

#196 fixed menu issue
  index.html
  script.js
  styles.css
Labels: apertre, Easy

#197 Card shadow
  contact.css
  styles.css
Labels: apertre, Easy

#199 Add Good Font style for various Browsers
  styles.css
Labels: apertre, Easy

#200 Update font of input box of Contact page
  contact.css
Labels: apertre, Easy
